### ISSUE TITLE
Not support variables call

### ISSUE THREAD

**Issue by fortil** [jonschlinkert/write-yaml#2]
Hi

I need this file 
```yml
service: ApiFile
custom:
  dev: ${file(variables.json):dev}
  prod: ${file(variables.json):prod}
  beta: ${file(variables.json):beta}
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  region: ${opt:region, 'us-east-2'}
  timeout: 10
  deploymentBucket:
    name: ${opt:bukect, 'translate-elixir-node-functions'}
  environment:
    HOST_DB: ${self:custom.${opt:stage, 'dev'}.HOST_DB}
    USER_DB: ${self:custom.${opt:stage, 'dev'}.USER_DB}
    PWD_DB: ${self:custom.${opt:stage, 'dev'}.PWD_DB}
    NAME_DB: ${self:custom.${opt:stage, 'dev'}.NAME_DB}
    PORT_DB: ${self:custom.${opt:stage, 'dev'}.PORT_DB}
    PEM: ${self:custom.${opt:stage, 'dev'}.PEM}
    STAGE: ${opt:stage, 'dev'}
functions:
  getEsriToken:
    handler: EsriToken
    description: This function get token from esri
    events:
      - http:
          path: esriToken
          method: get

```
But when put 
```json
{
  "service": "ApiFile",
  "custom": {
    "dev": "${file(variables.json):dev}",
    "prod": "${file(variables.json):prod}",
    "beta": "${file(variables.json):beta}"
  },
  "provider": {
    "name": "aws",
    "stage": "${opt:stage, 'dev'}",
    "runtime": "nodejs6.10",
    "region": "${opt:region, 'us-east-2'}",
    "timeout": 10,
    "deploymentBucket": {
      "name": "${opt:bukect, ''translate-elixir-node-functions''}"
    },
    "environment": {
      "HOST_DB": "${self:custom.${opt:stage, 'dev'}.HOST_DB}",
      "USER_DB": "${self:custom.${opt:stage, 'dev'}.USER_DB}",
      "PWD_DB": "${self:custom.${opt:stage, 'dev'}.PWD_DB}",
      "NAME_DB": "${self:custom.${opt:stage, 'dev'}.NAME_DB}",
      "PORT_DB": "${self:custom.${opt:stage, 'dev'}.PORT_DB}",
      "PEM": "${self:custom.${opt:stage, 'dev'}.PEM}",
      "STAGE": "${opt:stage, 'dev'}"
    }
  },
  "functions": {
    "getEsriToken": {
      "handler": "compiled/lidar.getEsriToken",
      "description": "This function get token from esri",
      "events": [
        {
          "http": {
            "path": "getEsriToken",
            "method": "get"
          }
        }
      ]
    }
  }
}
```
Its gen 
```yml
service: ApiFile
custom:
  dev: '${file(variables.json):dev}'
  prod: '${file(variables.json):prod}'
  beta: '${file(variables.json):beta}'
provider:
  name: aws
  stage: '${opt:stage, ''dev''}'
  runtime: nodejs6.10
  region: '${opt:region, ''us-east-2''}'
  timeout: 10
  deploymentBucket:
    name: '${opt:bukect, ''''translate-elixir-node-functions''''}'
  environment:
    HOST_DB: '${self:custom.${opt:stage, ''dev''}.HOST_DB}'
    USER_DB: '${self:custom.${opt:stage, ''dev''}.USER_DB}'
    PWD_DB: '${self:custom.${opt:stage, ''dev''}.PWD_DB}'
    NAME_DB: '${self:custom.${opt:stage, ''dev''}.NAME_DB}'
    PORT_DB: '${self:custom.${opt:stage, ''dev''}.PORT_DB}'
    PEM: '${self:custom.${opt:stage, ''dev''}.PEM}'
    STAGE: '${opt:stage, ''dev''}'
functions:
  getEsriToken:
    handler: compiled/lidar.getEsriToken
    description: This function get token from esri
    events:
      - http:
          path: getEsriToken
          method: get

```
Code with `'` in the vars, what I can to do?
thanks
